# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_swork_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swork',
            name='code',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='swork',
            name='memo',
            field=models.TextField(default=b''),
        ),
    ]
