# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-02 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160911_0721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
